spring.application.name=patchnotes
spring.datasource.url=jdbc:postgresql://db.ufsctwpvyoflhchapelj.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=Keiann-ureeves@1432425246374791
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
app.jwt.secret=patchnotes_super_secret_key_2024_do_not_share
app.jwt.expiration=86400000
spring.main.allow-circular-references=true